### ISSUE TITLE
How to add vector tiles from Ordnance Survey?

### ISSUE THREAD

**Issue by slead** [ted-piotrowski/react-leaflet-vector-tile-layer#3]
Thanks for writing this tool! Do you know how to add vector tiles hosted by someone other than Mapbox or Maptiler?

I'm trying to add vector tiles from Ordnance Survey, as shown in their demo at https://labs.os.uk/public/os-data-hub-examples/os-vector-tile-api/vts-3857-basic-map

They manually add some Mapbox vector tile libraries:

```
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.13.1/mapbox-gl.js"></script>
<script src="https://unpkg.com/mapbox-gl-leaflet/leaflet-mapbox-gl.js"></script>
```

then add the tiles using:

```
// Load and display vector tile layer on the map.
var gl = L.mapboxGL({
    style: 'https://api.os.uk/maps/vector/v1/vts/resources/styles?key=' + apiKey,
    transformRequest: url => {
        return {
            url: url += '&srs=3857'
        }
    }
})
```

Can I use your library to achieve this in React Leaflet? I tried using:

```
<VectorTileLayer
  styleUrl="https://api.os.uk/maps/vector/v1/vts/resources/styles?key=my-key"
/>
```

but this doesn't display on the map, although I do see a PBF file was downloaded in the developer tools. I've verified that my Ordnance Survey API key is valid in the stand-alone (non-React) demo.

Do you have any advice? thanks

**Comment by ted-piotrowski** [comment]
Hi Stephen. It's a bit hard for me to debug without an os.uk API key but if it works with MapboxGL, it should work with this plugin. In your examples I don't see you passing a `transformRequest` property into VectorTileLayer. Could this be the issue?

```
<VectorTileLayer
  styleUrl="https://api.os.uk/maps/vector/v1/vts/resources/styles?key=my-key"
  transformRequest={url => { return { url: url += '&srs=3857' }}}
/>
```

**Comment by slead** [comment]
many thanks, that's fixed it.
