### ISSUE TITLE
mapboxgl is not a constructor

### ISSUE THREAD

**Issue by anksuthar** [ted-piotrowski/react-leaflet-vector-tile-layer#4]
![Screenshot from 2022-01-25 16-39-29](https://user-images.githubusercontent.com/14817101/150966194-74ce146c-bd5b-4019-ab67-e93855c50650.png)

I used maptiler api and react-leaflet-vector-tile-layer for display map but i get this error on react-leaflet-vector-tile-layer module 

"mapboxgl is not a constructor"

**Comment by ted-piotrowski** [comment]
Can you make sure you’re using the latest version in your package.json

**Comment by ted-piotrowski** [comment]
Hi @anksuthar , any update on this? The plugin used to be based on mapbox-gl-leaflet is past versions but not uses maplibre-gl-leaflet

https://github.com/ted-piotrowski/react-leaflet-vector-tile-layer/blob/main/src/index.ts#L18

The error you shared might indicate that you're using an old version. Try `rm -rf node_modules` and installing the latest version (0.1.3)
