### ISSUE TITLE
Add react-leaflet version

### ISSUE THREAD

**Issue by Ciloe** [ted-piotrowski/react-leaflet-vector-tile-layer#5]
Hi, I would like to add the peerDependencies from `react-leaflet` to add the version `4.x.x`

Is it possible ?

**Comment by ted-piotrowski** [comment]
Thanks for the improvement. One warning squashed at a time.

**Comment by Ciloe** [comment]
What is the warning ?

**Comment by ted-piotrowski** [comment]
`npm WARN XXX requires a peer of XXX but none was installed.`

This was the warning if you npm installed `react-leaflet-vector-tile-layer` and `react-leaflet@4.X` before your fix. So I meant that this warning should now be gone thanks to you.

**Comment by Ciloe** [comment]
It's working like a charm now !
