### ISSUE TITLE
Hiding repeated maps

### ISSUE THREAD

**Issue by hk-centaari** [ted-piotrowski/react-leaflet-vector-tile-layer#7]
Hey, 
I need to show only one map without repeating it. Is there any prop to do that? If so kindly share it. Thankls

**Comment by ted-piotrowski** [comment]
Could you provide a code example that's showing more than one map?

**Comment by hk-centaari** [comment]
> Could you provide a code example that's showing more than one map?

I don't have any use case for this package. So, i am good, Thanks.
